// Mock Obsidian-style vault tree + markdown content for the open file.
// Plain JS so it loads from a normal <script src>.

window.VAULT = {
  name: "Vault",
  open: "1. Projects/Markdown Reader/README.md",
  tree: [
    { type: "folder", name: "0. Inbox", open: false, children: [
      { type: "file", name: "quick capture.md" },
    ]},
    { type: "folder", name: "1. Projects", open: true, children: [
      { type: "folder", name: "Markdown Reader", open: true, children: [
        { type: "file", name: "README.md", active: true },
        { type: "file", name: "spec.md" },
        { type: "file", name: "todo.md" },
        { type: "file", name: "mockup.png" },
        { type: "file", name: ".gitignore" },
      ]},
      { type: "folder", name: "Garden refresh", open: false, children: [
        { type: "file", name: "plan.md" },
        { type: "file", name: "moodboard.md" },
        { type: "file", name: "hero.jpg" },
      ]},
    ]},
    { type: "folder", name: "2. Areas", open: false, children: [
      { type: "file", name: "Reading list.md" },
      { type: "file", name: "Health log.md" },
      { type: "file", name: "Finances.md" },
    ]},
    { type: "folder", name: "3. Resources", open: true, children: [
      { type: "folder", name: "Snippets", open: false, children: [
        { type: "file", name: "css tricks.md" },
        { type: "file", name: "git aliases.md" },
        { type: "file", name: "color tokens.json" },
      ]},
      { type: "file", name: "Bookmarks.md" },
      { type: "file", name: "Quotes.md" },
    ]},
    { type: "folder", name: "4. Archive", open: false, children: [
      { type: "file", name: "2025 notes.md" },
    ]},
    { type: "file", name: "daily.md" },
    { type: "file", name: "index.md" },
  ],
};

// The markdown content currently open. Plain string, raw markdown.
window.MARKDOWN = [
  "# Markdown Reader",
  "",
  "A small, OS-native reader for browsing a folder of markdown notes.",
  "No accounts, no sync, no servers — just files on disk.",
  "",
  "The goal is to *get out of the way*: open a folder, click a file,",
  "read. Headings, code, and tables are rendered cleanly; everything",
  "else stays close to the source text.",
  "",
  "## Why",
  "",
  "Most readers either pretend to be a word processor or pretend to",
  "be an IDE. Neither is right for **reading notes**. This one tries",
  "to feel like the native Files app on whichever OS it's running on.",
  "",
  "## Architecture",
  "",
  "The reader has three jobs:",
  "",
  "1. Watch a folder for `*.md` files",
  "2. Parse the active file into a tree of blocks",
  "3. Render that tree into the right pane",
  "",
  "### Sidebar",
  "",
  "The left pane is a segmented control with two views:",
  "",
  "- **Folder** — the file tree of the opened folder",
  "- **Outline** — the headings in the current file, nested",
  "",
  "Only one is visible at a time.",
  "",
  "### Renderer",
  "",
  "A tiny pipeline. Headings keep their level. Code blocks get",
  "language-tagged so the highlighter can paint them. Tables are",
  "rendered as real `<table>` elements so they inherit native styling.",
  "",
  "## Keybindings",
  "",
  "| Key         | Action                  |",
  "| ----------- | ----------------------- |",
  "| Ctrl + 1    | Show folder pane        |",
  "| Ctrl + 2    | Show outline pane       |",
  "| Ctrl + P    | Quick open file         |",
  "| Ctrl + B    | Toggle sidebar          |",
  "| Ctrl + ,    | Preferences             |",
  "",
  "## Code style",
  "",
  "Components are intentionally tiny. A heading is just:",
  "",
  "```js",
  "function Heading({ level, children }) {",
  "  const Tag = `h${level}`;",
  "  return <Tag className=\"md-h\">{children}</Tag>;",
  "}",
  "```",
  "",
  "The parser is one pass, no AST library:",
  "",
  "```js",
  "function parse(src) {",
  "  const lines = src.split(\"\\n\");",
  "  const blocks = [];",
  "  let i = 0;",
  "  while (i < lines.length) {",
  "    const line = lines[i];",
  "    if (line.startsWith(\"#\")) {",
  "      blocks.push(heading(line));",
  "      i += 1;",
  "    } else if (isFence(line)) {",
  "      i = codeFence(lines, i, blocks);",
  "    } else {",
  "      i = paragraph(lines, i, blocks);",
  "    }",
  "  }",
  "  return blocks;",
  "}",
  "```",
  "",
  "## Status",
  "",
  "The reader is intentionally small and is not trying to be Obsidian.",
  "If a feature isn't on this list, it probably isn't coming.",
  "",
  "## ✅ Done",
  "",
  "Things already shipped, kept around for context. The outline can",
  "auto-collapse this section so it doesn't take up space.",
  "",
  "### Folder pane ✅",
  "",
  "Tree view with collapsible folders, opens .md files on click.",
  "",
  "### Outline pane ✅",
  "",
  "Nested headings, collapsible at each level.",
  "",
  "### Light / dark theming ✅",
  "",
  "Per-window toggle that retints the OS chrome too.",
  "",
].join("\n");
